#makefile, makefile

CC = gcc
#MODULE_NAME = data_types_and_sizes
target = encapsulation
OUTPUT = $(target)
SOURCE = $(target).c

$(OUTPUT):
#	$(CC) -o $(OUTPUT) -c $(SOURCE)
	$(CC) -o $(OUTPUT) $(SOURCE)
	
clean: 
	cp -u -r ./ ../make_clean_backup
	rm *.o $(target)

